import { NextRequest, NextResponse } from 'next/server'

export const runtime = 'edge'
export const dynamic = 'force-dynamic'

/**
 * DISABLED: Prediction generation is now handled exclusively by the Railway scraper (v4.0+)
 * This endpoint was creating duplicate/conflicting predictions.
 * Kept as a stub to avoid 404 errors from any lingering cron configs.
 */
export async function GET(request: NextRequest) {
    return NextResponse.json({
        success: true,
        message: 'Predictions are generated by Railway scraper. This endpoint is disabled.',
        timestamp: new Date().toISOString()
    })
}
